spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db24111
    username: dbid241
    password: dbpass241
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL ?? ?? ??
        "[user_sql_comments]": true     #SQL ??? ?? ??
        "[highlight_sql]": true         #SQL ??
        "[hbm2ddl.auto]":
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: true
    show-sql: true


  #default 1MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: 66qH64yA66qHKG1kbSntjIAg7KG47JeF7ZSE66Gc7KCd7Yq4IO2GteqzvO2VmOqyjCDtlbTso7zshLjsmpQuIOygnOuwnOyalC4uLi4g7ZiE7J6l7Iuk7Iq1IOqwgOq4sCDsi6vslrTsmpQg44Wg44Wg
  tokenExpirationTime: 18000

project:
  folderPath: "files/"

